sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t lha5/docker-react-learning -f Dockerfile.dev .

script:
    - docker run -e CI=true lha5/docker-react-learning npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket_name: "elasticbeanstalk-ap-northeast-2-209821040118"
    bucket_path: "docker-react-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY